### ISSUE TITLE
Delta of note on event is randomly increased after encoding

### ISSUE THREAD

**Issue by maximedupre** [chrisguttandin/json-midi-encoder#233]
When encoding the following JSON representation:

	{
		"division": 480,
		"format": 0,
		"tracks": [
			[
				{
					"noteOn": {
						"noteNumber": 60,
						"velocity": 100
					},
					"channel": 0,
					"delta": 0
				},
				{
					"noteOff": {
						"noteNumber": 60,
						"velocity": 100
					},
					"channel": 0,
					"delta": 1920
				},
				{
					"noteOn": {
						"noteNumber": 54,
						"velocity": 100
					},
					"channel": 0,
					"delta": 34560
				},
				{
					"noteOff": {
						"noteNumber": 54,
						"velocity": 100
					},
					"channel": 0,
					"delta": 1920
				},
				{
					"setTempo": {
						"microsecondsPerBeat": 500000
					},
					"channel": 0,
					"delta": 0
				}
			]
		]
	}

And decoding it right back, the delta value for the second note has changed for no reason:

	{
		"division": 480,
		"format": 0,
		"tracks": [
			[
				{
					"noteOn": {
						"noteNumber": 60,
						"velocity": 100
					},
					"channel": 0,
					"delta": 0
				},
				{
					"noteOff": {
						"noteNumber": 60,
						"velocity": 100
					},
					"channel": 0,
					"delta": 1920
				},
				{
					"noteOn": {
						"noteNumber": 54,
						"velocity": 100
					},
					"channel": 0,
					"delta": 229376
				},
				{
					"noteOff": {
						"noteNumber": 54,
						"velocity": 100
					},
					"channel": 0,
					"delta": 1920
				},
				{
					"setTempo": {
						"microsecondsPerBeat": 500000
					},
					"delta": 0
				}
			]
		]
	}

As you can see, for the second note on, the delta changed from 34560 to 229376.

**Comment by chrisguttandin** [comment]
Hi @maximedupre, thanks for reporting this. I will try to have a look at it in the next days.

Do you maybe know when the error happens? During encoding or decoding?

**Comment by maximedupre** [comment]
Hey @chrisguttandin ! Unfortunately I have no idea when the error occurs. It is impossible to know at my level of abstraction. Thanks for responding. Cheers!

**Comment by chrisguttandin** [comment]
Hi @maximedupre thanks again for reporting this. I discovered that values which need to be encoded as variable length quantity were not encoded correctly if 3 or more bytes were necessary. This should be fixed now.

**Comment by maximedupre** [comment]
I confirm it works! Thanks for the quick fix :)
